### PR TITLE
Chandana

### PR DESCRIPTION
**Pull request by chandanabobburi**
Hi Ms Gunde Neha,
I'm Chandana successfully completed my task.

### CODE REVIEW

**Comment by nehagunde** [comment]
ok get lost

**Comment by chandanabobburi** [comment]
Respect my work or ill quit ur company
ull see great loss

**Comment by nehagunde** [comment]
thats what i want get out
our company wont encourage such nastic people like u

**Comment by chandanabobburi** [comment]
ok lets go for outing together

**Comment by nehagunde** [comment]
chiiii ..yaakkkk.......thu....

**Comment by chandanabobburi** [comment]
ninu pilvadamee ekuva natkalu eyaku moskoni ra podam

**Pull request merged**
